module.exports={
    devServer:{
        proxy:{
            "/api":{
                target:"http://wthrcdn.etouch.cn/weather_mini",
                changeOrigin:true,
                pathRewrite:{
                    "^/api":""
                }
            }
        }
    }
}